development:
  clients:
    default:
      database: nauth_test
      hosts:
        - 10.255.8.148:27017
production:
  clients:
    default:
      database: nauth
      hosts:
        - 10.255.8.148:27017

