development:
  clients:
    default:
      database: nothing
      hosts:
        - localhost:27017
    nauth:
      database: nauth_test
      hosts:
        - localhost:27017
production:
  clients:
    default:
      database: nothing
      hosts:
        - localhost:27017
    nauth:
      database: nauth
      hosts:
        - localhost:27017

